# Use the official Node.js image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Tell Docker the app uses port 5000
EXPOSE 5000

# Start the application
CMD ["npm", "start"]